ladies = Category.create(name: "レディース")

ladies_tops = ladies.children.create(name: "トップス")
ladies_tops.children.create([{name:"Tシャツ/カットソー(半袖/袖なし)"}])
ladies_tops.children.create([{name:"Tシャツ/カットソー(七分/長袖)"}])
ladies_tops.children.create([{name:"シャツ/ブラウス(半袖/袖なし)"}])
ladies_tops.children.create([{name:"シャツ/ブラウス(七分/長袖)"}])
ladies_tops.children.create([{name:"ポロシャツ"}])
ladies_tops.children.create([{name:"キャミソール"}])
ladies_tops.children.create([{name:"タンクトップ"}])
ladies_tops.children.create([{name:"ホルターネック"}])
ladies_tops.children.create([{name:"ニット/セーター"}])
ladies_tops.children.create([{name:"チュニック"}])
ladies_tops.children.create([{name:"カーディガン/ボレロ"}])
ladies_tops.children.create([{name:"アンサンブル"}])
ladies_tops.children.create([{name:"ベスト/ジレ"}])
ladies_tops.children.create([{name:"パーカー"}])
ladies_tops.children.create([{name:"トレーナー/スウェット"}])
ladies_tops.children.create([{name:"ベアトップ/チューブトップ"}])
ladies_tops.children.create([{name:"ジャージ"}])
ladies_tops.children.create([{name:"その他"}])

ladies_outers = ladies.children.create(name: "ジャケット/アウター")
ladies_outers.children.create([{name:"テーラードジャケット"}])
ladies_outers.children.create([{name:"ノーカラージャケット"}])
ladies_outers.children.create([{name:"Gジャン/デニムジャケット"}])
ladies_outers.children.create([{name:"レザージャケット"}])
ladies_outers.children.create([{name:"ダウンジャケット"}])
ladies_outers.children.create([{name:"ライダースジャケット"}])
ladies_outers.children.create([{name:"ミリタリージャケット"}])
ladies_outers.children.create([{name:"ダウンベスト"}])
ladies_outers.children.create([{name:"ジャンパー/ブルゾン"}])
ladies_outers.children.create([{name:"ポンチョ"}])
ladies_outers.children.create([{name:"ロングコート"}])
ladies_outers.children.create([{name:"トレンチコート"}])
ladies_outers.children.create([{name:"ダッフルコート"}])
ladies_outers.children.create([{name:"ピーコート"}])
ladies_outers.children.create([{name:"チェスターコート"}])
ladies_outers.children.create([{name:"モッズコート"}])
ladies_outers.children.create([{name:"スタジャン"}])
ladies_outers.children.create([{name:"毛皮/ファーコート"}])
ladies_outers.children.create([{name:"スプリングコート"}])
ladies_outers.children.create([{name:"スカジャン"}])
ladies_outers.children.create([{name:"その他"}])

ladies_pants = ladies.children.create(name: "パンツ")
ladies_pants.children.create([{name:"デニム/ジーンズ"}])
ladies_pants.children.create([{name:"ショートパンツ"}])
ladies_pants.children.create([{name:"カジュアルパンツ"}])
ladies_pants.children.create([{name:"ハーフパンツ"}])
ladies_pants.children.create([{name:"チノパン"}])
ladies_pants.children.create([{name:"ワークパンツ/カーゴパンツ"}])
ladies_pants.children.create([{name:"クロップドパンツ"}])
ladies_pants.children.create([{name:"サロペット/オーバーオール"}])
ladies_pants.children.create([{name:"オールインワン"}])
ladies_pants.children.create([{name:"サルエルパンツ"}])
ladies_pants.children.create([{name:"ガウチョパンツ"}])
ladies_pants.children.create([{name:"その他"}])
ladies_pants.children.create([{name:"スカート"}])
ladies_pants.children.create([{name:"ミニスカート"}])
ladies_pants.children.create([{name:"ひざ丈スカート"}])
ladies_pants.children.create([{name:"ロングスカート"}])
ladies_pants.children.create([{name:"キュロット"}])
ladies_pants.children.create([{name:"その他"}])
ladies_pants.children.create([{name:"ワンピース"}])
ladies_pants.children.create([{name:"ミニワンピース"}])
ladies_pants.children.create([{name:"ひざ丈ワンピース"}])
ladies_pants.children.create([{name:"ロングワンピース"}])
ladies_pants.children.create([{name:"その他"}])


ladies_skirts = ladies.children.create(name: "スカート")
ladies_skirts.children.create([{name:"ミニスカート"}])
ladies_skirts.children.create([{name:"ひざ丈スカート"}])
ladies_skirts.children.create([{name:"ロングスカート"}])
ladies_skirts.children.create([{name:"キュロット"}])
ladies_skirts.children.create([{name:"その他"}])

ladies_dress = ladies.children.create(name: "ワンピース")
ladies_dress.children.create([{name:"ミニワンピース"}])
ladies_dress.children.create([{name:"ひざ丈ワンピース"}])
ladies_dress.children.create([{name:"ロングワンピース"}])
ladies_dress.children.create([{name:"その他"}])

ladies_shoes = ladies.children.create(name: "靴")
ladies_shoes.children.create([{name:"ハイヒール/パンプス"}])
ladies_shoes.children.create([{name:"ブーツ"}])
ladies_shoes.children.create([{name:"サンダル"}])
ladies_shoes.children.create([{name:"スニーカー"}])
ladies_shoes.children.create([{name:"ミュール"}])
ladies_shoes.children.create([{name:"モカシン"}])
ladies_shoes.children.create([{name:"ローファー/革靴"}])
ladies_shoes.children.create([{name:"フラットシューズ/バレエシューズ"}])
ladies_shoes.children.create([{name:"長靴/レインシューズ"}])
ladies_shoes.children.create([{name:"その他"}])

ladies_roomwares = ladies.children.create(name: "ルームウェア/パジャマ")
ladies_roomwares.children.create([{name:"パジャマ"}])
ladies_roomwares.children.create([{name:"ルームウェア"}])



ladies_legwares = ladies.children.create(name: "レッグウェア")
ladies_legwares.children.create([{name:"ソックス"}])
ladies_legwares.children.create([{name:"スパッツ/レギンス"}])
ladies_legwares.children.create([{name:"ストッキング/タイツ"}])
ladies_legwares.children.create([{name:"レッグウォーマー"}])
ladies_legwares.children.create([{name:"その他"}])


ladies_hats = ladies.children.create(name: "帽子")
ladies_hats.children.create([{name:"ニットキャップ/ビーニー"}])
ladies_hats.children.create([{name:"ハット"}])
ladies_hats.children.create([{name:"ハンチング/ベレー帽"}])
ladies_hats.children.create([{name:"キャップ"}])
ladies_hats.children.create([{name:"キャスケット"}])
ladies_hats.children.create([{name:"麦わら帽子"}])
ladies_hats.children.create([{name:"その他"}])


ladies_bags = ladies.children.create(name: "バッグ")
ladies_bags.children.create([{name:"ハンドバッグ"}])
ladies_bags.children.create([{name:"トートバッグ"}])
ladies_bags.children.create([{name:"エコバッグ"}])
ladies_bags.children.create([{name:"リュック/バックパック"}])
ladies_bags.children.create([{name:"ボストンバッグ"}])
ladies_bags.children.create([{name:"スポーツバッグ"}])
ladies_bags.children.create([{name:"ショルダーバッグ"}])
ladies_bags.children.create([{name:"クラッチバッグ"}])
ladies_bags.children.create([{name:"ポーチ/バニティ"}])
ladies_bags.children.create([{name:"ボディバッグ/ウェストバッグ"}])
ladies_bags.children.create([{name:"マザーズバッグ"}])
ladies_bags.children.create([{name:"メッセンジャーバッグ"}])
ladies_bags.children.create([{name:"ビジネスバッグ"}])
ladies_bags.children.create([{name:"旅行用バッグ/キャリーバッグ"}])
ladies_bags.children.create([{name:"ショップ袋"}])
ladies_bags.children.create([{name:"和装用バッグ"}])
ladies_bags.children.create([{name:"かごバッグ"}])
ladies_bags.children.create([{name:"その他"}])


ladies_accesories = ladies.children.create(name: "アクセサリー")
ladies_accesories.children.create([{name:"ネックレス"}])
ladies_accesories.children.create([{name:"ブレスレット"}])
ladies_accesories.children.create([{name:"バングル/リストバンド"}])
ladies_accesories.children.create([{name:"リング"}])
ladies_accesories.children.create([{name:"ピアス(片耳用)"}])
ladies_accesories.children.create([{name:"ピアス(両耳用)"}])
ladies_accesories.children.create([{name:"イヤリング"}])
ladies_accesories.children.create([{name:"アンクレット"}])
ladies_accesories.children.create([{name:"ブローチ/コサージュ"}])
ladies_accesories.children.create([{name:"チャーム"}])
ladies_accesories.children.create([{name:"その他"}])


ladies_hairaccesories = ladies.children.create(name: "ヘアアクセサリー")
ladies_hairaccesories.children.create([{name:"ヘアゴム/シュシュ"}])
ladies_hairaccesories.children.create([{name:"ヘアバンド/カチューシャ"}])
ladies_hairaccesories.children.create([{name:"ヘアピン"}])
ladies_hairaccesories.children.create([{name:"その他"}])

ladies_smallones = ladies.children.create(name: "小物")
ladies_smallones.children.create([{name:"長財布"}])
ladies_smallones.children.create([{name:"折り財布"}])
ladies_smallones.children.create([{name:"コインケース/小銭入れ"}])
ladies_smallones.children.create([{name:"名刺入れ/定期入れ"}])
ladies_smallones.children.create([{name:"キーケース"}])
ladies_smallones.children.create([{name:"キーホルダー"}])
ladies_smallones.children.create([{name:"手袋/アームカバー"}])
ladies_smallones.children.create([{name:"ハンカチ"}])
ladies_smallones.children.create([{name:"ベルト"}])
ladies_smallones.children.create([{name:"マフラー/ショール"}])
ladies_smallones.children.create([{name:"ストール/スヌード"}])
ladies_smallones.children.create([{name:"バンダナ/スカーフ"}])
ladies_smallones.children.create([{name:"ネックウォーマー"}])
ladies_smallones.children.create([{name:"サスペンダー"}])
ladies_smallones.children.create([{name:"サングラス/メガネ"}])
ladies_smallones.children.create([{name:"モバイルケース/カバー"}])
ladies_smallones.children.create([{name:"手帳"}])
ladies_smallones.children.create([{name:"イヤマフラー"}])
ladies_smallones.children.create([{name:"傘"}])
ladies_smallones.children.create([{name:"レインコート/ポンチョ"}])
ladies_smallones.children.create([{name:"ミラー"}])
ladies_smallones.children.create([{name:"タバコグッズ"}])
ladies_smallones.children.create([{name:"その他"}])

ladies_watches = ladies.children.create(name: "時計")
ladies_watches.children.create([{name:"腕時計(アナログ)"}])
ladies_watches.children.create([{name:"腕時計(デジタル)"}])
ladies_watches.children.create([{name:"ラバーベルト"}])
ladies_watches.children.create([{name:"レザーベルト"}])
ladies_watches.children.create([{name:"金属ベルト"}])
ladies_watches.children.create([{name:"その他"}])

ladies_wigs = ladies.children.create(name: "ウィッグ/エクステ")
ladies_wigs.children.create([{name:"前髪ウィッグ"}])
ladies_wigs.children.create([{name:"ロングストレート"}])
ladies_wigs.children.create([{name:"ロングカール"}])
ladies_wigs.children.create([{name:"ショートストレート"}])
ladies_wigs.children.create([{name:"ショートカール"}])
ladies_wigs.children.create([{name:"その他"}])


ladies_yukatas = ladies.children.create(name: "浴衣/水着")
ladies_yukatas.children.create([{name:"浴衣"}])
ladies_yukatas.children.create([{name:"着物"}])
ladies_yukatas.children.create([{name:"振袖"}])
ladies_yukatas.children.create([{name:"長襦袢/半襦袢"}])
ladies_yukatas.children.create([{name:"水着セパレート"}])
ladies_yukatas.children.create([{name:"水着ワンピース"}])
ladies_yukatas.children.create([{name:"水着スポーツ用"}])
ladies_yukatas.children.create([{name:"その他"}])


ladies_suits = ladies.children.create(name: "スーツ/フォーマル/ドレス")
ladies_suits.children.create([{name:"スカートスーツ上下"}])
ladies_suits.children.create([{name:"パンツスーツ上下"}])
ladies_suits.children.create([{name:"ドレス"}])
ladies_suits.children.create([{name:"パーティーバッグ"}])
ladies_suits.children.create([{name:"シューズ"}])
ladies_suits.children.create([{name:"ウェディング"}])
ladies_suits.children.create([{name:"その他"}])

ladies_maternities = ladies.children.create(name: "マタニティ")
ladies_maternities.children.create([{name:"マタニティ"}])
ladies_maternities.children.create([{name:"トップス"}])
ladies_maternities.children.create([{name:"アウター"}])
ladies_maternities.children.create([{name:"インナー"}])
ladies_maternities.children.create([{name:"ワンピース"}])
ladies_maternities.children.create([{name:"パンツ/スパッツ"}])
ladies_maternities.children.create([{name:"スカート"}])
ladies_maternities.children.create([{name:"パジャマ"}])
ladies_maternities.children.create([{name:"授乳服"}])
ladies_maternities.children.create([{name:"その他"}])


ladies_others = ladies.children.create(name: "その他")
ladies_others.children.create([{name:"コスプレ"}])
ladies_others.children.create([{name:"下着"}])
ladies_others.children.create([{name:"その他"}])

mens = Category.create(name: "メンズ")

mens_tops = mens.children.create(name: "トップス")
mens_tops.children.create([{name:"Tシャツ/カットソー(半袖/袖なし)"}])
mens_tops.children.create([{name:"Tシャツ/カットソー(七分/長袖)"}])
mens_tops.children.create([{name:"シャツ"}])
mens_tops.children.create([{name:"ポロシャツ"}])
mens_tops.children.create([{name:"タンクトップ"}])
mens_tops.children.create([{name:"ニット/セーター"}])
mens_tops.children.create([{name:"パーカー"}])
mens_tops.children.create([{name:"カーディガン"}])
mens_tops.children.create([{name:"スウェット"}])
mens_tops.children.create([{name:"ジャージ"}])
mens_tops.children.create([{name:"ベスト"}])
mens_tops.children.create([{name:"その他"}])


mens_outers = mens.children.create(name: "ジャケット/アウター")
mens_outers.children.create([{name:"テーラードジャケット"}])
mens_outers.children.create([{name:"ノーカラージャケット"}])
mens_outers.children.create([{name:"Gジャン/デニムジャケット"}])
mens_outers.children.create([{name:"レザージャケット"}])
mens_outers.children.create([{name:"ダウンジャケット"}])
mens_outers.children.create([{name:"ライダースジャケット"}])
mens_outers.children.create([{name:"ミリタリージャケット"}])
mens_outers.children.create([{name:"ナイロンジャケット"}])
mens_outers.children.create([{name:"フライトジャケット"}])
mens_outers.children.create([{name:"ダッフルコート"}])
mens_outers.children.create([{name:"ピーコート"}])
mens_outers.children.create([{name:"ステンカラーコート"}])
mens_outers.children.create([{name:"トレンチコート"}])
mens_outers.children.create([{name:"モッズコート"}])
mens_outers.children.create([{name:"チェスターコート"}])
mens_outers.children.create([{name:"スタジャン"}])
mens_outers.children.create([{name:"スカジャン"}])
mens_outers.children.create([{name:"ブルゾン"}])
mens_outers.children.create([{name:"マウンテンパーカー"}])
mens_outers.children.create([{name:"ダウンベスト"}])
mens_outers.children.create([{name:"ポンチョ"}])
mens_outers.children.create([{name:"カバーオール"}])
mens_outers.children.create([{name:"その他"}])

mens_pants = mens.children.create(name: "パンツ")
mens_pants.children.create([{name:"デニム/ジーンズ"}])
mens_pants.children.create([{name:"ワークパンツ/カーゴパンツ"}])
mens_pants.children.create([{name:"スラックス"}])
mens_pants.children.create([{name:"チノパン"}])
mens_pants.children.create([{name:"ショートパンツ"}])
mens_pants.children.create([{name:"ペインターパンツ"}])
mens_pants.children.create([{name:"サルエルパンツ"}])
mens_pants.children.create([{name:"オーバーオール"}])
mens_pants.children.create([{name:"その他"}])

mens_shoes = mens.children.create(name: "靴")
mens_shoes.children.create([{name:"スニーカー"}])
mens_shoes.children.create([{name:"サンダル"}])
mens_shoes.children.create([{name:"ブーツ"}])
mens_shoes.children.create([{name:"モカシン"}])
mens_shoes.children.create([{name:"ドレス/ビジネス"}])
mens_shoes.children.create([{name:"長靴/レインシューズ"}])
mens_shoes.children.create([{name:"デッキシューズ"}])
mens_shoes.children.create([{name:"その他"}])


mens_bags = mens.children.create(name: "バッグ")
mens_bags.children.create([{name:"ショルダーバッグ"}])
mens_bags.children.create([{name:"トートバッグ"}])
mens_bags.children.create([{name:"ボストンバッグ"}])
mens_bags.children.create([{name:"リュック/バックパック"}])
mens_bags.children.create([{name:"ウエストポーチ"}])
mens_bags.children.create([{name:"ボディーバッグ"}])
mens_bags.children.create([{name:"ドラムバッグ"}])
mens_bags.children.create([{name:"ビジネスバッグ"}])
mens_bags.children.create([{name:"トラベルバッグ"}])
mens_bags.children.create([{name:"メッセンジャーバッグ"}])
mens_bags.children.create([{name:"エコバッグ"}])
mens_bags.children.create([{name:"その他"}])

mens_suits = mens.children.create(name: "スーツ")
mens_suits.children.create([{name:"スーツジャケット"}])
mens_suits.children.create([{name:"スーツベスト"}])
mens_suits.children.create([{name:"スラックス"}])
mens_suits.children.create([{name:"セットアップ"}])
mens_suits.children.create([{name:"その他"}])


mens_hats = mens.children.create(name: "帽子")
mens_hats.children.create([{name:"キャップ"}])
mens_hats.children.create([{name:"ハット"}])
mens_hats.children.create([{name:"ニットキャップ/ビーニー"}])
mens_hats.children.create([{name:"ハンチング/ベレー帽"}])
mens_hats.children.create([{name:"キャスケット"}])
mens_hats.children.create([{name:"サンバイザー"}])
mens_hats.children.create([{name:"その他"}])


mens_accesories = mens.children.create(name: "アクセサリー")
mens_accesories.children.create([{name:"ネックレス"}])
mens_accesories.children.create([{name:"ブレスレット"}])
mens_accesories.children.create([{name:"バングル/リストバンド"}])
mens_accesories.children.create([{name:"リング"}])
mens_accesories.children.create([{name:"ピアス(片耳用)"}])
mens_accesories.children.create([{name:"ピアス(両耳用)"}])
mens_accesories.children.create([{name:"アンクレット"}])
mens_accesories.children.create([{name:"その他"}])

mens_smallones = mens.children.create(name: "小物")
mens_smallones.children.create([{name:"長財布"}])
mens_smallones.children.create([{name:"折り財布"}])
mens_smallones.children.create([{name:"マネークリップ"}])
mens_smallones.children.create([{name:"コインケース/小銭入れ"}])
mens_smallones.children.create([{name:"名刺入れ/定期入れ"}])
mens_smallones.children.create([{name:"キーケース"}])
mens_smallones.children.create([{name:"キーホルダー"}])
mens_smallones.children.create([{name:"ネクタイ"}])
mens_smallones.children.create([{name:"手袋"}])
mens_smallones.children.create([{name:"ハンカチ"}])
mens_smallones.children.create([{name:"ベルト"}])
mens_smallones.children.create([{name:"マフラー"}])
mens_smallones.children.create([{name:"ストール"}])
mens_smallones.children.create([{name:"バンダナ"}])
mens_smallones.children.create([{name:"ネックウォーマー"}])
mens_smallones.children.create([{name:"サスペンダー"}])
mens_smallones.children.create([{name:"ウォレットチェーン"}])
mens_smallones.children.create([{name:"サングラス/メガネ"}])
mens_smallones.children.create([{name:"モバイルケース/カバー"}])
mens_smallones.children.create([{name:"手帳"}])
mens_smallones.children.create([{name:"ストラップ"}])
mens_smallones.children.create([{name:"ネクタイピン"}])
mens_smallones.children.create([{name:"カフリンクス"}])
mens_smallones.children.create([{name:"イヤマフラー"}])
mens_smallones.children.create([{name:"傘"}])
mens_smallones.children.create([{name:"レインコート"}])
mens_smallones.children.create([{name:"ミラー"}])
mens_smallones.children.create([{name:"タバコグッズ"}])
mens_smallones.children.create([{name:"その他"}])

mens_watches = mens.children.create(name: "時計")
mens_watches.children.create([{name:"腕時計(アナログ)"}])
mens_watches.children.create([{name:"腕時計(デジタル)"}])
mens_watches.children.create([{name:"ラバーベルト"}])
mens_watches.children.create([{name:"レザーベルト"}])
mens_watches.children.create([{name:"金属ベルト"}])
mens_watches.children.create([{name:"その他"}])



mens_swimsuits = mens.children.create(name: "水着")
mens_swimsuits.children.create([{name:"一般水着"}])
mens_swimsuits.children.create([{name:"スポーツ用"}])
mens_swimsuits.children.create([{name:"アクセサリー"}])
mens_swimsuits.children.create([{name:"その他"}])

mens_legwares = mens.children.create(name: "レッグウェア")
mens_legwares.children.create([{name:"ソックス"}])
mens_legwares.children.create([{name:"レギンス/スパッツ"}])
mens_legwares.children.create([{name:"レッグウォーマー"}])
mens_legwares.children.create([{name:"その他"}])

mens_underwares = mens.children.create(name: "アンダーウェア")
mens_underwares.children.create([{name:"トランクス"}])
mens_underwares.children.create([{name:"ボクサーパンツ"}])
mens_underwares.children.create([{name:"その他"}])

mens_others = mens.children.create(name: "その他")

babies = Category.create(name: "ベビー・キッズ")

babies_girl_u95 = babies.children.create(name: "ベビー服(女の子用)  ~95cm")
babies_girl_u95.children.create([{name:"トップス"}])
babies_girl_u95.children.create([{name:"アウター"}])
babies_girl_u95.children.create([{name:"パンツ"}])
babies_girl_u95.children.create([{name:"スカート"}])
babies_girl_u95.children.create([{name:"ワンピース"}])
babies_girl_u95.children.create([{name:"ベビードレス"}])
babies_girl_u95.children.create([{name:"おくるみ"}])
babies_girl_u95.children.create([{name:"下着/肌着"}])
babies_girl_u95.children.create([{name:"パジャマ"}])
babies_girl_u95.children.create([{name:"ロンパース"}])
babies_girl_u95.children.create([{name:"その他"}])

babies_boy_u95 = babies.children.create(name: "ベビー服(男の子用)  ~95cm")
babies_boy_u95.children.create([{name:"トップス"}])
babies_boy_u95.children.create([{name:"アウター"}])
babies_boy_u95.children.create([{name:"パンツ"}])
babies_boy_u95.children.create([{name:"おくるみ"}])
babies_boy_u95.children.create([{name:"下着/肌着"}])
babies_boy_u95.children.create([{name:"パジャマ"}])
babies_boy_u95.children.create([{name:"ロンパース"}])
babies_boy_u95.children.create([{name:"その他"}])

babies_uni_u95 = babies.children.create(name: "ベビー服(男女兼用)  ~95cm")
babies_uni_u95.children.create([{name:"トップス"}])
babies_uni_u95.children.create([{name:"アウター"}])
babies_uni_u95.children.create([{name:"パンツ"}])
babies_uni_u95.children.create([{name:"おくるみ"}])
babies_uni_u95.children.create([{name:"下着/肌着"}])
babies_uni_u95.children.create([{name:"パジャマ"}])
babies_uni_u95.children.create([{name:"ロンパース"}])
babies_uni_u95.children.create([{name:"その他"}])

babies_girl_o100 = babies.children.create(name: "キッズ服(女の子用) 100cm~")
babies_girl_o100.children.create([{name:"コート"}])
babies_girl_o100.children.create([{name:"ジャケット/上着"}])
babies_girl_o100.children.create([{name:"トップス(Tシャツ/カットソー)"}])
babies_girl_o100.children.create([{name:"トップス(トレーナー)"}])
babies_girl_o100.children.create([{name:"トップス(チュニック)"}])
babies_girl_o100.children.create([{name:"トップス(タンクトップ)"}])
babies_girl_o100.children.create([{name:"トップス(その他)"}])
babies_girl_o100.children.create([{name:"スカート"}])
babies_girl_o100.children.create([{name:"パンツ"}])
babies_girl_o100.children.create([{name:"ワンピース"}])
babies_girl_o100.children.create([{name:"セットアップ"}])
babies_girl_o100.children.create([{name:"パジャマ"}])
babies_girl_o100.children.create([{name:"フォーマル/ドレス"}])
babies_girl_o100.children.create([{name:"和服"}])
babies_girl_o100.children.create([{name:"浴衣"}])
babies_girl_o100.children.create([{name:"甚平"}])
babies_girl_o100.children.create([{name:"水着"}])
babies_girl_o100.children.create([{name:"その他"}])

babies_boy_o100 = babies.children.create(name: "キッズ服(男の子用) 100cm~")
babies_boy_o100.children.create([{name:"コート"}])
babies_boy_o100.children.create([{name:"ジャケット/上着"}])
babies_boy_o100.children.create([{name:"トップス(Tシャツ/カットソー)"}])
babies_boy_o100.children.create([{name:"トップス(トレーナー)"}])
babies_boy_o100.children.create([{name:"トップス(その他)"}])
babies_boy_o100.children.create([{name:"パンツ"}])
babies_boy_o100.children.create([{name:"セットアップ"}])
babies_boy_o100.children.create([{name:"パジャマ"}])
babies_boy_o100.children.create([{name:"フォーマル/ドレス"}])
babies_boy_o100.children.create([{name:"和服"}])
babies_boy_o100.children.create([{name:"浴衣"}])
babies_boy_o100.children.create([{name:"甚平"}])
babies_boy_o100.children.create([{name:"水着"}])
babies_boy_o100.children.create([{name:"その他"}])

babies_uni_o100 = babies.children.create(name: "キッズ服(男女兼用) 100cm~")
babies_uni_o100.children.create([{name:"キッズ服(男女兼用) 100cm~"}])
babies_uni_o100.children.create([{name:"コート"}])
babies_uni_o100.children.create([{name:"ジャケット/上着"}])
babies_uni_o100.children.create([{name:"トップス(Tシャツ/カットソー)"}])
babies_uni_o100.children.create([{name:"トップス(トレーナー)"}])
babies_uni_o100.children.create([{name:"トップス(その他)"}])
babies_uni_o100.children.create([{name:"ボトムス"}])
babies_uni_o100.children.create([{name:"パジャマ"}])
babies_uni_o100.children.create([{name:"その他"}])

babies_shoes = babies.children.create(name: "キッズ靴")
babies_shoes.children.create([{name:"スニーカー"}])
babies_shoes.children.create([{name:"サンダル"}])
babies_shoes.children.create([{name:"ブーツ"}])
babies_shoes.children.create([{name:"長靴"}])
babies_shoes.children.create([{name:"その他"}])

babies_smallones = babies.children.create(name: "子ども用ファッション小物")
babies_smallones.children.create([{name:"靴下/スパッツ"}])
babies_smallones.children.create([{name:"帽子"}])
babies_smallones.children.create([{name:"エプロン"}])
babies_smallones.children.create([{name:"サスペンダー"}])
babies_smallones.children.create([{name:"タイツ"}])
babies_smallones.children.create([{name:"ハンカチ"}])
babies_smallones.children.create([{name:"バンダナ"}])
babies_smallones.children.create([{name:"ベルト"}])
babies_smallones.children.create([{name:"マフラー"}])
babies_smallones.children.create([{name:"傘"}])
babies_smallones.children.create([{name:"手袋"}])
babies_smallones.children.create([{name:"スタイ"}])
babies_smallones.children.create([{name:"バッグ"}])
babies_smallones.children.create([{name:"その他"}])


babies_baths = babies.children.create(name: "おむつ/トイレ/バス")
babies_baths.children.create([{name:"おむつ/トイレ/バス"}])
babies_baths.children.create([{name:"おむつ用品"}])
babies_baths.children.create([{name:"おまる/補助便座"}])
babies_baths.children.create([{name:"トレーニングパンツ"}])
babies_baths.children.create([{name:"ベビーバス"}])
babies_baths.children.create([{name:"お風呂用品"}])
babies_baths.children.create([{name:"その他"}])



babies_outdoors = babies.children.create(name: "外出/移動用品")
babies_outdoors.children.create([{name:"ベビーカー"}])
babies_outdoors.children.create([{name:"抱っこひも/スリング"}])
babies_outdoors.children.create([{name:"チャイルドシート"}])
babies_outdoors.children.create([{name:"その他"}])

babies_meals = babies.children.create(name: "授乳/食事")
babies_meals.children.create([{name:"ミルク"}])
babies_meals.children.create([{name:"ベビーフード"}])
babies_meals.children.create([{name:"ベビー用食器"}])
babies_meals.children.create([{name:"その他"}])


babies_furnitures = babies.children.create(name: "ベビー家具/寝具/室内用品")
babies_furnitures.children.create([{name:"ベッド"}])
babies_furnitures.children.create([{name:"布団/毛布"}])
babies_furnitures.children.create([{name:"イス"}])
babies_furnitures.children.create([{name:"たんす"}])
babies_furnitures.children.create([{name:"その他"}])



babies_toies = babies.children.create(name: "おもちゃ")
babies_toies.children.create([{name:"おふろのおもちゃ"}])
babies_toies.children.create([{name:"がらがら"}])
babies_toies.children.create([{name:"オルゴール"}])
babies_toies.children.create([{name:"ベビージム"}])
babies_toies.children.create([{name:"手押し車/カタカタ"}])
babies_toies.children.create([{name:"知育玩具"}])
babies_toies.children.create([{name:"その他"}])


babies_souvenirs = babies.children.create(name: "行事/記念品")
babies_souvenirs.children.create([{name:"お宮参り用品"}])
babies_souvenirs.children.create([{name:"お食い初め用品"}])
babies_souvenirs.children.create([{name:"アルバム"}])
babies_souvenirs.children.create([{name:"手形/足形"}])
babies_souvenirs.children.create([{name:"その他"}])


babies_others = babies.children.create(name: "その他")
babies_others.children.create([{name:"母子手帳用品"}])
babies_others.children.create([{name:"その他"}])


cosmes = Category.create(name: "コスメ・香水・美容")

cosmes_basemakes = cosmes.children.create(name: "ベースメイク")
cosmes_basemakes.children.create([{name:"ファンデーション"}])
cosmes_basemakes.children.create([{name:"化粧下地"}])
cosmes_basemakes.children.create([{name:"コントロールカラー"}])
cosmes_basemakes.children.create([{name:"BBクリーム"}])
cosmes_basemakes.children.create([{name:"CCクリーム"}])
cosmes_basemakes.children.create([{name:"コンシーラー"}])
cosmes_basemakes.children.create([{name:"フェイスパウダー"}])
cosmes_basemakes.children.create([{name:"トライアルセット/サンプル"}])
cosmes_basemakes.children.create([{name:"その他"}])


cosmes_makeups = cosmes.children.create(name: "メイクアップ")
cosmes_makeups.children.create([{name:"アイシャドウ"}])
cosmes_makeups.children.create([{name:"口紅"}])
cosmes_makeups.children.create([{name:"リップグロス"}])
cosmes_makeups.children.create([{name:"リップライナー"}])
cosmes_makeups.children.create([{name:"チーク"}])
cosmes_makeups.children.create([{name:"フェイスカラー"}])
cosmes_makeups.children.create([{name:"マスカラ"}])
cosmes_makeups.children.create([{name:"アイライナー"}])
cosmes_makeups.children.create([{name:"つけまつげ"}])
cosmes_makeups.children.create([{name:"アイブロウペンシル"}])
cosmes_makeups.children.create([{name:"パウダーアイブロウ"}])
cosmes_makeups.children.create([{name:"眉マスカラ"}])
cosmes_makeups.children.create([{name:"トライアルセット/サンプル"}])
cosmes_makeups.children.create([{name:"メイク道具/化粧小物"}])
cosmes_makeups.children.create([{name:"美顔用品/美顔ローラー"}])
cosmes_makeups.children.create([{name:"その他"}])

cosmes_nailcares = cosmes.children.create(name: "ネイルケア")
cosmes_nailcares.children.create([{name:"ネイルカラー"}])
cosmes_nailcares.children.create([{name:"カラージェル"}])
cosmes_nailcares.children.create([{name:"ネイルベースコート/トップコート"}])
cosmes_nailcares.children.create([{name:"ネイルアート用品"}])
cosmes_nailcares.children.create([{name:"ネイルパーツ"}])
cosmes_nailcares.children.create([{name:"ネイルチップ/付け爪"}])
cosmes_nailcares.children.create([{name:"手入れ用具"}])
cosmes_nailcares.children.create([{name:"除光液"}])
cosmes_nailcares.children.create([{name:"その他"}])

cosmes_perfumes = cosmes.children.create(name: "香水")
cosmes_perfumes.children.create([{name:"香水(女性用)"}])
cosmes_perfumes.children.create([{name:"香水(男性用)"}])
cosmes_perfumes.children.create([{name:"ユニセックス"}])
cosmes_perfumes.children.create([{name:"ボディミスト"}])
cosmes_perfumes.children.create([{name:"その他"}])


cosmes_skincares = cosmes.children.create(name: "スキンケア/基礎化粧品")
cosmes_skincares.children.create([{name:"化粧水/ローション"}])
cosmes_skincares.children.create([{name:"乳液/ミルク"}])
cosmes_skincares.children.create([{name:"美容液"}])
cosmes_skincares.children.create([{name:"フェイスクリーム"}])
cosmes_skincares.children.create([{name:"洗顔料"}])
cosmes_skincares.children.create([{name:"クレンジング/メイク落とし"}])
cosmes_skincares.children.create([{name:"パック/フェイスマスク"}])
cosmes_skincares.children.create([{name:"ジェル/ゲル"}])
cosmes_skincares.children.create([{name:"ブースター/導入液"}])
cosmes_skincares.children.create([{name:"アイケア"}])
cosmes_skincares.children.create([{name:"リップケア"}])
cosmes_skincares.children.create([{name:"トライアルセット/サンプル"}])
cosmes_skincares.children.create([{name:"洗顔グッズ"}])
cosmes_skincares.children.create([{name:"その他"}])

cosmes_haircares = cosmes.children.create(name: "ヘアケア")
cosmes_haircares.children.create([{name:"シャンプー"}])
cosmes_haircares.children.create([{name:"トリートメント"}])
cosmes_haircares.children.create([{name:"コンディショナー"}])
cosmes_haircares.children.create([{name:"リンス"}])
cosmes_haircares.children.create([{name:"スタイリング剤"}])
cosmes_haircares.children.create([{name:"カラーリング剤"}])
cosmes_haircares.children.create([{name:"ブラシ"}])
cosmes_haircares.children.create([{name:"その他"}])

cosmes_bodycares = cosmes.children.create(name: "ボディケア")
cosmes_bodycares.children.create([{name:"オイル/クリーム"}])
cosmes_bodycares.children.create([{name:"ハンドクリーム"}])
cosmes_bodycares.children.create([{name:"ローション"}])
cosmes_bodycares.children.create([{name:"日焼け止め/サンオイル"}])
cosmes_bodycares.children.create([{name:"ボディソープ"}])
cosmes_bodycares.children.create([{name:"入浴剤"}])
cosmes_bodycares.children.create([{name:"制汗/デオドラント"}])
cosmes_bodycares.children.create([{name:"フットケア"}])
cosmes_bodycares.children.create([{name:"その他"}])

cosmes_oralcares = cosmes.children.create(name: "オーラルケア")
cosmes_oralcares.children.create([{name:"口臭防止/エチケット用品"}])
cosmes_oralcares.children.create([{name:"歯ブラシ"}])
cosmes_oralcares.children.create([{name:"その他"}])

cosmes_relaxations = cosmes.children.create(name: "リラクゼーション")
cosmes_relaxations.children.create([{name:"エッセンシャルオイル"}])
cosmes_relaxations.children.create([{name:"芳香器"}])
cosmes_relaxations.children.create([{name:"お香/香炉"}])
cosmes_relaxations.children.create([{name:"キャンドル"}])
cosmes_relaxations.children.create([{name:"リラクゼーショングッズ"}])
cosmes_relaxations.children.create([{name:"その他"}])

cosmes_diets = cosmes.children.create(name: "ダイエット")
cosmes_diets.children.create([{name:"ダイエット食品"}])
cosmes_diets.children.create([{name:"エクササイズ用品"}])
cosmes_diets.children.create([{name:"体重計"}])
cosmes_diets.children.create([{name:"体脂肪計"}])
cosmes_diets.children.create([{name:"その他"}])

cosmes_others = cosmes.children.create(name: "その他")
cosmes_others.children.create([{name:"健康用品"}])
cosmes_others.children.create([{name:"看護/介護用品"}])
cosmes_others.children.create([{name:"救急/衛生用品"}])
cosmes_others.children.create([{name:"その他"}])


interiors = Category.create(name: "インテリア・住まい・小物")

interiors_kitchentools = interiors.children.create(name: "キッチン/食器")
interiors_kitchentools.children.create([{name:"食器"}])
interiors_kitchentools.children.create([{name:"調理器具"}])
interiors_kitchentools.children.create([{name:"収納/キッチン雑貨"}])
interiors_kitchentools.children.create([{name:"弁当用品"}])
interiors_kitchentools.children.create([{name:"カトラリー(スプーン等)"}])
interiors_kitchentools.children.create([{name:"テーブル用品"}])
interiors_kitchentools.children.create([{name:"容器"}])
interiors_kitchentools.children.create([{name:"エプロン"}])
interiors_kitchentools.children.create([{name:"アルコールグッズ"}])
interiors_kitchentools.children.create([{name:"浄水機"}])
interiors_kitchentools.children.create([{name:"その他"}])

interiors_beds = interiors.children.create(name: "ベッド/マットレス")
interiors_beds.children.create([{name:"セミシングルベッド"}])
interiors_beds.children.create([{name:"シングルベッド"}])
interiors_beds.children.create([{name:"セミダブルベッド"}])
interiors_beds.children.create([{name:"ダブルベッド"}])
interiors_beds.children.create([{name:"ワイドダブルベッド"}])
interiors_beds.children.create([{name:"クイーンベッド"}])
interiors_beds.children.create([{name:"キングベッド"}])
interiors_beds.children.create([{name:"脚付きマットレスベッド"}])
interiors_beds.children.create([{name:"マットレス"}])
interiors_beds.children.create([{name:"すのこベッド"}])
interiors_beds.children.create([{name:"ロフトベッド/システムベッド"}])
interiors_beds.children.create([{name:"簡易ベッド/折りたたみベッド"}])
interiors_beds.children.create([{name:"収納付き"}])
interiors_beds.children.create([{name:"その他"}])

interiors_sofas = interiors.children.create(name: "ソファ/ソファベッド")
interiors_sofas.children.create([{name:"ソファセット"}])
interiors_sofas.children.create([{name:"シングルソファ"}])
interiors_sofas.children.create([{name:"ラブソファ"}])
interiors_sofas.children.create([{name:"トリプルソファ"}])
interiors_sofas.children.create([{name:"オットマン"}])
interiors_sofas.children.create([{name:"コーナーソファ"}])
interiors_sofas.children.create([{name:"ビーズソファ/クッションソファ"}])
interiors_sofas.children.create([{name:"ローソファ/フロアソファ"}])
interiors_sofas.children.create([{name:"ソファベッド"}])
interiors_sofas.children.create([{name:"応接セット"}])
interiors_sofas.children.create([{name:"ソファカバー"}])
interiors_sofas.children.create([{name:"リクライニングソファ"}])
interiors_sofas.children.create([{name:"その他"}])

interiors_chairs = interiors.children.create(name: "椅子/チェア")
interiors_chairs.children.create([{name:"一般"}])
interiors_chairs.children.create([{name:"スツール"}])
interiors_chairs.children.create([{name:"ダイニングチェア"}])
interiors_chairs.children.create([{name:"ハイバックチェア"}])
interiors_chairs.children.create([{name:"ロッキングチェア"}])
interiors_chairs.children.create([{name:"座椅子"}])
interiors_chairs.children.create([{name:"折り畳みイス"}])
interiors_chairs.children.create([{name:"デスクチェア"}])
interiors_chairs.children.create([{name:"その他"}])

interiors_desks = interiors.children.create(name: "机/テーブル")
interiors_desks.children.create([{name:"こたつ"}])
interiors_desks.children.create([{name:"カウンターテーブル"}])
interiors_desks.children.create([{name:"サイドテーブル"}])
interiors_desks.children.create([{name:"センターテーブル"}])
interiors_desks.children.create([{name:"ダイニングテーブル"}])
interiors_desks.children.create([{name:"座卓/ちゃぶ台"}])
interiors_desks.children.create([{name:"アウトドア用"}])
interiors_desks.children.create([{name:"パソコン用"}])
interiors_desks.children.create([{name:"事務机/学習机"}])
interiors_desks.children.create([{name:"その他"}])

interiors_boxes = interiors.children.create(name: "収納家具")
interiors_boxes.children.create([{name:"リビング収納"}])
interiors_boxes.children.create([{name:"キッチン収納"}])
interiors_boxes.children.create([{name:"玄関/屋外収納"}])
interiors_boxes.children.create([{name:"バス/トイレ収納"}])
interiors_boxes.children.create([{name:"本収納"}])
interiors_boxes.children.create([{name:"本/CD/DVD収納"}])
interiors_boxes.children.create([{name:"洋服タンス/押入れ収納"}])
interiors_boxes.children.create([{name:"電話台/ファックス台"}])
interiors_boxes.children.create([{name:"ドレッサー/鏡台"}])
interiors_boxes.children.create([{name:"棚/ラック"}])
interiors_boxes.children.create([{name:"ケース/ボックス"}])
interiors_boxes.children.create([{name:"その他"}])

interiors_rugs = interiors.children.create(name: "ラグ/カーペット/マット")
interiors_rugs.children.create([{name:"ラグ"}])
interiors_rugs.children.create([{name:"カーペット"}])
interiors_rugs.children.create([{name:"ホットカーペット"}])
interiors_rugs.children.create([{name:"玄関/キッチンマット"}])
interiors_rugs.children.create([{name:"トイレ/バスマット"}])
interiors_rugs.children.create([{name:"その他"}])

interiors_curtains = interiors.children.create(name: "カーテン/ブラインド")
interiors_curtains.children.create([{name:"カーテン"}])
interiors_curtains.children.create([{name:"ブラインド"}])
interiors_curtains.children.create([{name:"ロールスクリーン"}])
interiors_curtains.children.create([{name:"のれん"}])
interiors_curtains.children.create([{name:"その他"}])

interiors_lights = interiors.children.create(name: "ライト/照明")
interiors_lights.children.create([{name:"蛍光灯/電球"}])
interiors_lights.children.create([{name:"天井照明"}])
interiors_lights.children.create([{name:"フロアスタンド"}])
interiors_lights.children.create([{name:"その他"}])

interiors_beddings = interiors.children.create(name: "寝具")
interiors_beddings.children.create([{name:"布団/毛布"}])
interiors_beddings.children.create([{name:"枕"}])
interiors_beddings.children.create([{name:"シーツ/カバー"}])
interiors_beddings.children.create([{name:"その他"}])

interiors_interiorsmallones = interiors.children.create(name: "インテリア小物")
interiors_interiorsmallones.children.create([{name:"ごみ箱"}])
interiors_interiorsmallones.children.create([{name:"ウェルカムボード"}])
interiors_interiorsmallones.children.create([{name:"オルゴール"}])
interiors_interiorsmallones.children.create([{name:"クッション"}])
interiors_interiorsmallones.children.create([{name:"クッションカバー"}])
interiors_interiorsmallones.children.create([{name:"スリッパラック"}])
interiors_interiorsmallones.children.create([{name:"ティッシュボックス"}])
interiors_interiorsmallones.children.create([{name:"バスケット/かご"}])
interiors_interiorsmallones.children.create([{name:"フォトフレーム"}])
interiors_interiorsmallones.children.create([{name:"マガジンラック"}])
interiors_interiorsmallones.children.create([{name:"モビール"}])
interiors_interiorsmallones.children.create([{name:"花瓶"}])
interiors_interiorsmallones.children.create([{name:"灰皿"}])
interiors_interiorsmallones.children.create([{name:"傘立て"}])
interiors_interiorsmallones.children.create([{name:"小物入れ"}])
interiors_interiorsmallones.children.create([{name:"置時計"}])
interiors_interiorsmallones.children.create([{name:"掛時計/柱時計"}])
interiors_interiorsmallones.children.create([{name:"鏡(立て掛け式)"}])
interiors_interiorsmallones.children.create([{name:"鏡(壁掛け式)"}])
interiors_interiorsmallones.children.create([{name:"置物"}])
interiors_interiorsmallones.children.create([{name:"風鈴"}])
interiors_interiorsmallones.children.create([{name:"植物/観葉植物"}])
interiors_interiorsmallones.children.create([{name:"その他"}])

interiors_seasons = interiors.children.create(name: "季節/年中行事")
interiors_seasons.children.create([{name:"正月"}])
interiors_seasons.children.create([{name:"成人式"}])
interiors_seasons.children.create([{name:"バレンタインデー"}])
interiors_seasons.children.create([{name:"ひな祭り"}])
interiors_seasons.children.create([{name:"子どもの日"}])
interiors_seasons.children.create([{name:"母の日"}])
interiors_seasons.children.create([{name:"父の日"}])
interiors_seasons.children.create([{name:"サマーギフト/お中元"}])
interiors_seasons.children.create([{name:"夏/夏休み"}])
interiors_seasons.children.create([{name:"ハロウィン"}])
interiors_seasons.children.create([{name:"敬老の日"}])
interiors_seasons.children.create([{name:"七五三"}])
interiors_seasons.children.create([{name:"お歳暮"}])
interiors_seasons.children.create([{name:"クリスマス"}])
interiors_seasons.children.create([{name:"冬一般"}])
interiors_seasons.children.create([{name:"その他"}])

interiors_others = interiors.children.create(name: "その他")




books = Category.create(name: "本・音楽・ゲーム")

books_books = books.children.create(name: "本")
books_books.children.create([{name:"文学/小説"}])
books_books.children.create([{name:"人文/社会"}])
books_books.children.create([{name:"ノンフィクション/教養"}])
books_books.children.create([{name:"地図/旅行ガイド"}])
books_books.children.create([{name:"ビジネス/経済"}])
books_books.children.create([{name:"健康/医学"}])
books_books.children.create([{name:"コンピュータ/IT"}])
books_books.children.create([{name:"趣味/スポーツ/実用"}])
books_books.children.create([{name:"住まい/暮らし/子育て"}])
books_books.children.create([{name:"アート/エンタメ"}])
books_books.children.create([{name:"洋書"}])
books_books.children.create([{name:"絵本"}])
books_books.children.create([{name:"参考書"}])
books_books.children.create([{name:"その他"}])

books_mangas = books.children.create(name: "漫画")
books_mangas.children.create([{name:"全巻セット"}])
books_mangas.children.create([{name:"少年漫画"}])
books_mangas.children.create([{name:"少女漫画"}])
books_mangas.children.create([{name:"青年漫画"}])
books_mangas.children.create([{name:"女性漫画"}])
books_mangas.children.create([{name:"同人誌"}])
books_mangas.children.create([{name:"その他"}])

books_magazines = books.children.create(name: "雑誌")
books_magazines.children.create([{name:"アート/エンタメ/ホビー"}])
books_magazines.children.create([{name:"ファッション"}])
books_magazines.children.create([{name:"ニュース/総合"}])
books_magazines.children.create([{name:"趣味/スポーツ"}])
books_magazines.children.create([{name:"その他"}])

books_cds = books.children.create(name: "CD")
books_cds.children.create([{name:"邦楽"}])
books_cds.children.create([{name:"洋楽"}])
books_cds.children.create([{name:"アニメ"}])
books_cds.children.create([{name:"クラシック"}])
books_cds.children.create([{name:"K-POP/アジア"}])
books_cds.children.create([{name:"キッズ/ファミリー"}])
books_cds.children.create([{name:"その他"}])

books_dvds = books.children.create(name: "DVD/ブルーレイ")
books_dvds.children.create([{name:"外国映画"}])
books_dvds.children.create([{name:"日本映画"}])
books_dvds.children.create([{name:"アニメ"}])
books_dvds.children.create([{name:"TVドラマ"}])
books_dvds.children.create([{name:"ミュージック"}])
books_dvds.children.create([{name:"お笑い/バラエティ"}])
books_dvds.children.create([{name:"スポーツ/フィットネス"}])
books_dvds.children.create([{name:"キッズ/ファミリー"}])
books_dvds.children.create([{name:"その他"}])

books_records = books.children.create(name: "レコード")
books_records.children.create([{name:"邦楽"}])
books_records.children.create([{name:"洋楽"}])
books_records.children.create([{name:"その他"}])

books_tvgames = books.children.create(name: "テレビゲーム")
books_tvgames.children.create([{name:"家庭用ゲーム本体"}])
books_tvgames.children.create([{name:"家庭用ゲームソフト"}])
books_tvgames.children.create([{name:"携帯用ゲーム本体"}])
books_tvgames.children.create([{name:"携帯用ゲームソフト"}])
books_tvgames.children.create([{name:"PCゲーム"}])
books_tvgames.children.create([{name:"その他"}])

toies = Category.create(name: "おもちゃ・ホビー・グッズ")

toies_toies = toies.children.create(name: "おもちゃ")
toies_toies.children.create([{name:"キャラクターグッズ"}])
toies_toies.children.create([{name:"ぬいぐるみ"}])
toies_toies.children.create([{name:"小物/アクセサリー"}])
toies_toies.children.create([{name:"模型/プラモデル"}])
toies_toies.children.create([{name:"ミニカー"}])
toies_toies.children.create([{name:"トイラジコン"}])
toies_toies.children.create([{name:"プラモデル"}])
toies_toies.children.create([{name:"ホビーラジコン"}])
toies_toies.children.create([{name:"鉄道模型"}])
toies_toies.children.create([{name:"その他"}])

toies_goods = toies.children.create(name: "タレントグッズ")
toies_goods.children.create([{name:"アイドル"}])
toies_goods.children.create([{name:"ミュージシャン"}])
toies_goods.children.create([{name:"タレント/お笑い芸人"}])
toies_goods.children.create([{name:"スポーツ選手"}])
toies_goods.children.create([{name:"その他"}])

toies_comics = toies.children.create(name: "コミック/アニメグッズ")
toies_comics.children.create([{name:"ストラップ"}])
toies_comics.children.create([{name:"キーホルダー"}])
toies_comics.children.create([{name:"バッジ"}])
toies_comics.children.create([{name:"カード"}])
toies_comics.children.create([{name:"クリアファイル"}])
toies_comics.children.create([{name:"ポスター"}])
toies_comics.children.create([{name:"タオル"}])
toies_comics.children.create([{name:"その他"}])

toies_tradingcards = toies.children.create(name: "トレーディングカード")
toies_tradingcards.children.create([{name:"遊戯王"}])
toies_tradingcards.children.create([{name:"マジック：ザ・ギャザリング"}])
toies_tradingcards.children.create([{name:"ポケモンカードゲーム"}])
toies_tradingcards.children.create([{name:"デュエルマスターズ"}])
toies_tradingcards.children.create([{name:"バトルスピリッツ"}])
toies_tradingcards.children.create([{name:"プリパラ"}])
toies_tradingcards.children.create([{name:"アイカツ"}])
toies_tradingcards.children.create([{name:"カードファイト!! ヴァンガード"}])
toies_tradingcards.children.create([{name:"ヴァイスシュヴァルツ"}])
toies_tradingcards.children.create([{name:"プロ野球オーナーズリーグ"}])
toies_tradingcards.children.create([{name:"ベースボールヒーローズ"}])
toies_tradingcards.children.create([{name:"ドラゴンボール"}])
toies_tradingcards.children.create([{name:"スリーブ"}])
toies_tradingcards.children.create([{name:"その他"}])

toies_figures = toies.children.create(name: "フィギュア")
toies_figures.children.create([{name:"コミック/アニメ"}])
toies_figures.children.create([{name:"特撮"}])
toies_figures.children.create([{name:"ゲームキャラクター"}])
toies_figures.children.create([{name:"SF/ファンタジー/ホラー"}])
toies_figures.children.create([{name:"アメコミ"}])
toies_figures.children.create([{name:"スポーツ"}])
toies_figures.children.create([{name:"ミリタリー"}])
toies_figures.children.create([{name:"その他"}])

toies_furnitures = toies.children.create(name: "楽器/器材")
toies_furnitures.children.create([{name:"エレキギター"}])
toies_furnitures.children.create([{name:"アコースティックギター"}])
toies_furnitures.children.create([{name:"ベース"}])
toies_furnitures.children.create([{name:"エフェクター"}])
toies_furnitures.children.create([{name:"アンプ"}])
toies_furnitures.children.create([{name:"弦楽器"}])
toies_furnitures.children.create([{name:"管楽器"}])
toies_furnitures.children.create([{name:"鍵盤楽器"}])
toies_furnitures.children.create([{name:"打楽器"}])
toies_furnitures.children.create([{name:"和楽器"}])
toies_furnitures.children.create([{name:"楽譜/スコア"}])
toies_furnitures.children.create([{name:"レコーディング/PA機器"}])
toies_furnitures.children.create([{name:"DJ機器"}])
toies_furnitures.children.create([{name:"DTM/DAW"}])
toies_furnitures.children.create([{name:"その他"}])

toies_collections = toies.children.create(name: "コレクション")
toies_collections.children.create([{name:"武具"}])
toies_collections.children.create([{name:"使用済切手/官製はがき"}])
toies_collections.children.create([{name:"旧貨幣/金貨/銀貨/記念硬貨"}])
toies_collections.children.create([{name:"印刷物"}])
toies_collections.children.create([{name:"ノベルティグッズ"}])
toies_collections.children.create([{name:"その他"}])

toies_millitaries = toies.children.create(name: "ミリタリー")
toies_millitaries.children.create([{name:"トイガン"}])
toies_millitaries.children.create([{name:"個人装備"}])
toies_millitaries.children.create([{name:"その他"}])

toies_arts = toies.children.create(name: "美術品")
toies_arts.children.create([{name:"陶芸"}])
toies_arts.children.create([{name:"ガラス"}])
toies_arts.children.create([{name:"漆芸"}])
toies_arts.children.create([{name:"金属工芸"}])
toies_arts.children.create([{name:"絵画/タペストリ"}])
toies_arts.children.create([{name:"版画"}])
toies_arts.children.create([{name:"彫刻/オブジェクト"}])
toies_arts.children.create([{name:"書"}])
toies_arts.children.create([{name:"写真"}])
toies_arts.children.create([{name:"その他"}])

toies_arttools = toies.children.create(name: "アート用品")
toies_arttools.children.create([{name:"画材"}])
toies_arttools.children.create([{name:"額縁"}])
toies_arttools.children.create([{name:"その他"}])

toies_others = toies.children.create(name: "その他")
toies_others.children.create([{name:"トランプ/UNO"}])
toies_others.children.create([{name:"カルタ/百人一首"}])
toies_others.children.create([{name:"ダーツ"}])
toies_others.children.create([{name:"ビリヤード"}])
toies_others.children.create([{name:"麻雀"}])
toies_others.children.create([{name:"パズル/ジグソーパズル"}])
toies_others.children.create([{name:"囲碁/将棋"}])
toies_others.children.create([{name:"オセロ/チェス"}])
toies_others.children.create([{name:"人生ゲーム"}])
toies_others.children.create([{name:"野球/サッカーゲーム"}])
toies_others.children.create([{name:"スポーツ"}])
toies_others.children.create([{name:"三輪車/乗り物"}])
toies_others.children.create([{name:"ヨーヨー"}])
toies_others.children.create([{name:"模型製作用品"}])
toies_others.children.create([{name:"鉄道"}])
toies_others.children.create([{name:"航空機"}])
toies_others.children.create([{name:"アマチュア無線"}])
toies_others.children.create([{name:"パチンコ/パチスロ"}])
toies_others.children.create([{name:"その他"}])


electricdevices = Category.create(name: "家電・スマホ・カメラ")

electricdevices_smartphones = electricdevices.children.create(name: "スマートフォン/携帯電話")
electricdevices_smartphones.children.create([{name:"スマートフォン本体"}])
electricdevices_smartphones.children.create([{name:"バッテリー/充電器"}])
electricdevices_smartphones.children.create([{name:"携帯電話本体"}])
electricdevices_smartphones.children.create([{name:"PHS本体"}])
electricdevices_smartphones.children.create([{name:"その他"}])

electricdevices_smaphoaccesories = electricdevices.children.create(name: "スマホアクセサリー")
electricdevices_smaphoaccesories.children.create([{name:"Android用ケース"}])
electricdevices_smaphoaccesories.children.create([{name:"iPhone用ケース"}])
electricdevices_smaphoaccesories.children.create([{name:"カバー"}])
electricdevices_smaphoaccesories.children.create([{name:"イヤホンジャック"}])
electricdevices_smaphoaccesories.children.create([{name:"ストラップ"}])
electricdevices_smaphoaccesories.children.create([{name:"フィルム"}])
electricdevices_smaphoaccesories.children.create([{name:"自撮り棒"}])
electricdevices_smaphoaccesories.children.create([{name:"その他"}])

electricdevices_pcs = electricdevices.children.create(name: "PC/タブレット")
electricdevices_pcs.children.create([{name:"タブレット"}])
electricdevices_pcs.children.create([{name:"ノートPC"}])
electricdevices_pcs.children.create([{name:"デスクトップ型PC"}])
electricdevices_pcs.children.create([{name:"ディスプレイ"}])
electricdevices_pcs.children.create([{name:"電子ブックリーダー"}])
electricdevices_pcs.children.create([{name:"PC周辺機器"}])
electricdevices_pcs.children.create([{name:"PCパーツ"}])
electricdevices_pcs.children.create([{name:"その他"}])

electricdevices_cameras = electricdevices.children.create(name: "カメラ")
electricdevices_cameras.children.create([{name:"デジタルカメラ"}])
electricdevices_cameras.children.create([{name:"ビデオカメラ"}])
electricdevices_cameras.children.create([{name:"レンズ(単焦点)"}])
electricdevices_cameras.children.create([{name:"レンズ(ズーム)"}])
electricdevices_cameras.children.create([{name:"フィルムカメラ"}])
electricdevices_cameras.children.create([{name:"防犯カメラ"}])
electricdevices_cameras.children.create([{name:"その他"}])

electricdevices_tvs = electricdevices.children.create(name: "テレビ/映像機器")
electricdevices_tvs.children.create([{name:"テレビ"}])
electricdevices_tvs.children.create([{name:"プロジェクター"}])
electricdevices_tvs.children.create([{name:"ブルーレイレコーダー"}])
electricdevices_tvs.children.create([{name:"DVDレコーダー"}])
electricdevices_tvs.children.create([{name:"ブルーレイプレーヤー"}])
electricdevices_tvs.children.create([{name:"DVDプレーヤー"}])
electricdevices_tvs.children.create([{name:"映像用ケーブル"}])
electricdevices_tvs.children.create([{name:"その他"}])

electricdevices_audios = electricdevices.children.create(name: "オーディオ機器")
electricdevices_audios.children.create([{name:"ポータブルプレーヤー"}])
electricdevices_audios.children.create([{name:"イヤフォン"}])
electricdevices_audios.children.create([{name:"ヘッドフォン"}])
electricdevices_audios.children.create([{name:"アンプ"}])
electricdevices_audios.children.create([{name:"スピーカー"}])
electricdevices_audios.children.create([{name:"ケーブル/シールド"}])
electricdevices_audios.children.create([{name:"ラジオ"}])
electricdevices_audios.children.create([{name:"その他"}])

electricdevices_beauties = electricdevices.children.create(name: "美容/健康")
electricdevices_beauties.children.create([{name:"ヘアドライヤー"}])
electricdevices_beauties.children.create([{name:"ヘアアイロン"}])
electricdevices_beauties.children.create([{name:"美容機器"}])
electricdevices_beauties.children.create([{name:"電気シェーバー"}])
electricdevices_beauties.children.create([{name:"電動歯ブラシ"}])
electricdevices_beauties.children.create([{name:"その他"}])

electricdevices_conditioners = electricdevices.children.create(name: "冷暖房/空調")
electricdevices_conditioners.children.create([{name:"エアコン"}])
electricdevices_conditioners.children.create([{name:"空気清浄器"}])
electricdevices_conditioners.children.create([{name:"加湿器"}])
electricdevices_conditioners.children.create([{name:"扇風機"}])
electricdevices_conditioners.children.create([{name:"除湿機"}])
electricdevices_conditioners.children.create([{name:"ファンヒーター "}])
electricdevices_conditioners.children.create([{name:"電気ヒーター"}])
electricdevices_conditioners.children.create([{name:"オイルヒーター"}])
electricdevices_conditioners.children.create([{name:"ストーブ"}])
electricdevices_conditioners.children.create([{name:"ホットカーペット"}])
electricdevices_conditioners.children.create([{name:"こたつ"}])
electricdevices_conditioners.children.create([{name:"電気毛布"}])
electricdevices_conditioners.children.create([{name:"その他"}])

electricdevices_devices = electricdevices.children.create(name: "生活家電")
electricdevices_devices.children.create([{name:"冷蔵庫"}])
electricdevices_devices.children.create([{name:"洗濯機"}])
electricdevices_devices.children.create([{name:"炊飯器"}])
electricdevices_devices.children.create([{name:"電子レンジ/オーブン"}])
electricdevices_devices.children.create([{name:"調理機器"}])
electricdevices_devices.children.create([{name:"アイロン"}])
electricdevices_devices.children.create([{name:"掃除機"}])
electricdevices_devices.children.create([{name:"エスプレッソマシン"}])
electricdevices_devices.children.create([{name:"コーヒーメーカー"}])
electricdevices_devices.children.create([{name:"衣類乾燥機"}])
electricdevices_devices.children.create([{name:"その他"}])

electricdevices_others = electricdevices.children.create(name: "その他")
electricdevices_others.children.create([{name:"その他"}])

sports = Category.create(name: "スポーツ・レジャー")

sports_golfs = sports.children.create(name: "ゴルフ")
sports_golfs.children.create([{name:"クラブ"}])
sports_golfs.children.create([{name:"ウエア(男性用)"}])
sports_golfs.children.create([{name:"ウエア(女性用)"}])
sports_golfs.children.create([{name:"バッグ "}])
sports_golfs.children.create([{name:"シューズ(男性用)"}])
sports_golfs.children.create([{name:"シューズ(女性用)"}])
sports_golfs.children.create([{name:"アクセサリー"}])
sports_golfs.children.create([{name:"その他"}])

sports_fishings = sports.children.create(name: "フィッシング")
sports_fishings.children.create([{name:"ロッド"}])
sports_fishings.children.create([{name:"リール"}])
sports_fishings.children.create([{name:"ルアー用品"}])
sports_fishings.children.create([{name:"ウエア"}])
sports_fishings.children.create([{name:"釣り糸/ライン"}])
sports_fishings.children.create([{name:"その他"}])

sports_bikes = sports.children.create(name: "自転車")
sports_bikes.children.create([{name:"自転車本体"}])
sports_bikes.children.create([{name:"ウエア"}])
sports_bikes.children.create([{name:"パーツ"}])
sports_bikes.children.create([{name:"アクセサリー"}])
sports_bikes.children.create([{name:"バッグ"}])
sports_bikes.children.create([{name:"工具/メンテナンス"}])
sports_bikes.children.create([{name:"その他"}])

sports_trainings = sports.children.create(name: "トレーニング/エクササイズ")
sports_trainings.children.create([{name:"ランニング"}])
sports_trainings.children.create([{name:"ウォーキング"}])
sports_trainings.children.create([{name:"ヨガ"}])
sports_trainings.children.create([{name:"トレーニング用品"}])
sports_trainings.children.create([{name:"その他"}])

sports_baseballs = sports.children.create(name: "野球")
sports_baseballs.children.create([{name:"ウェア"}])
sports_baseballs.children.create([{name:"シューズ"}])
sports_baseballs.children.create([{name:"グローブ"}])
sports_baseballs.children.create([{name:"バット"}])
sports_baseballs.children.create([{name:"アクセサリー"}])
sports_baseballs.children.create([{name:"防具"}])
sports_baseballs.children.create([{name:"練習機器"}])
sports_baseballs.children.create([{name:"記念グッズ"}])
sports_baseballs.children.create([{name:"応援グッズ"}])
sports_baseballs.children.create([{name:"その他"}])

sports_soccers = sports.children.create(name: "サッカー/フットサル")
sports_soccers.children.create([{name:"ウェア"}])
sports_soccers.children.create([{name:"シューズ"}])
sports_soccers.children.create([{name:"ボール"}])
sports_soccers.children.create([{name:"アクセサリー"}])
sports_soccers.children.create([{name:"記念グッズ"}])
sports_soccers.children.create([{name:"応援グッズ"}])
sports_soccers.children.create([{name:"その他"}])

sports_tennises = sports.children.create(name: "テニス")
sports_tennises.children.create([{name:"ラケット(硬式用)"}])
sports_tennises.children.create([{name:"ラケット(軟式用)"}])
sports_tennises.children.create([{name:"ウェア"}])
sports_tennises.children.create([{name:"シューズ"}])
sports_tennises.children.create([{name:"ボール"}])
sports_tennises.children.create([{name:"アクセサリー"}])
sports_tennises.children.create([{name:"記念グッズ"}])
sports_tennises.children.create([{name:"応援グッズ"}])
sports_tennises.children.create([{name:"その他"}])

sports_snowboards = sports.children.create(name: "スノーボード")
sports_snowboards.children.create([{name:"ボード"}])
sports_snowboards.children.create([{name:"バインディング"}])
sports_snowboards.children.create([{name:"ブーツ(男性用)"}])
sports_snowboards.children.create([{name:"ブーツ(女性用)"}])
sports_snowboards.children.create([{name:"ブーツ(子ども用)"}])
sports_snowboards.children.create([{name:"ウエア/装備(男性用)"}])
sports_snowboards.children.create([{name:"ウエア/装備(女性用)"}])
sports_snowboards.children.create([{name:"ウエア/装備(子ども用)"}])
sports_snowboards.children.create([{name:"アクセサリー"}])
sports_snowboards.children.create([{name:"バッグ"}])
sports_snowboards.children.create([{name:"その他"}])

sports_skis = sports.children.create(name: "スキー")
sports_skis.children.create([{name:"板"}])
sports_skis.children.create([{name:"ブーツ(男性用)"}])
sports_skis.children.create([{name:"ブーツ(女性用)"}])
sports_skis.children.create([{name:"ブーツ(子ども用)"}])
sports_skis.children.create([{name:"ビンディング"}])
sports_skis.children.create([{name:"ウエア(男性用)"}])
sports_skis.children.create([{name:"ウエア(女性用)"}])
sports_skis.children.create([{name:"ウエア(子ども用)"}])
sports_skis.children.create([{name:"ストック"}])
sports_skis.children.create([{name:"その他"}])

sports_othersports = sports.children.create(name: "その他スポーツ")
sports_othersports.children.create([{name:"ダンス/バレエ"}])
sports_othersports.children.create([{name:"サーフィン"}])
sports_othersports.children.create([{name:"バスケットボール"}])
sports_othersports.children.create([{name:"バドミントン"}])
sports_othersports.children.create([{name:"バレーボール"}])
sports_othersports.children.create([{name:"スケートボード"}])
sports_othersports.children.create([{name:"陸上競技"}])
sports_othersports.children.create([{name:"ラグビー"}])
sports_othersports.children.create([{name:"アメリカンフットボール"}])
sports_othersports.children.create([{name:"ボクシング"}])
sports_othersports.children.create([{name:"ボウリング"}])
sports_othersports.children.create([{name:"その他"}])

sports_outdoors = sports.children.create(name: "アウトドア")
sports_outdoors.children.create([{name:"テント/タープ"}])
sports_outdoors.children.create([{name:"ライト/ランタン"}])
sports_outdoors.children.create([{name:"寝袋/寝具"}])
sports_outdoors.children.create([{name:"テーブル/チェア"}])
sports_outdoors.children.create([{name:"ストーブ/コンロ"}])
sports_outdoors.children.create([{name:"調理器具"}])
sports_outdoors.children.create([{name:"食器"}])
sports_outdoors.children.create([{name:"登山用品"}])
sports_outdoors.children.create([{name:"その他"}])

sports_others = sports.children.create(name: "その他")
sports_others.children.create([{name:"旅行用品"}])
sports_others.children.create([{name:"その他"}])


handmades = Category.create(name: "ハンドメイド")

handmades_girlsaccesories = handmades.children.create(name: "アクセサリー(女性用)")
handmades_girlsaccesories.children.create([{name:"ピアス"}])
handmades_girlsaccesories.children.create([{name:"イヤリング"}])
handmades_girlsaccesories.children.create([{name:"ネックレス"}])
handmades_girlsaccesories.children.create([{name:"ブレスレット"}])
handmades_girlsaccesories.children.create([{name:"リング"}])
handmades_girlsaccesories.children.create([{name:"チャーム"}])
handmades_girlsaccesories.children.create([{name:"ヘアゴム"}])
handmades_girlsaccesories.children.create([{name:"アンクレット"}])
handmades_girlsaccesories.children.create([{name:"その他"}])

handmades_fashions = handmades.children.create(name: "ファッション/小物")
handmades_fashions.children.create([{name:"バッグ(女性用)"}])
handmades_fashions.children.create([{name:"バッグ(男性用)"}])
handmades_fashions.children.create([{name:"財布(女性用)"}])
handmades_fashions.children.create([{name:"財布(男性用)"}])
handmades_fashions.children.create([{name:"ファッション雑貨"}])
handmades_fashions.children.create([{name:"その他"}])

handmades_watches = handmades.children.create(name: "アクセサリー/時計")
handmades_watches.children.create([{name:"アクセサリー(男性用)"}])
handmades_watches.children.create([{name:"時計(女性用)"}])
handmades_watches.children.create([{name:"時計(男性用)"}])
handmades_watches.children.create([{name:"その他"}])

handmades_interiors = handmades.children.create(name: "日用品/インテリア")
handmades_interiors.children.create([{name:"キッチン用品"}])
handmades_interiors.children.create([{name:"家具"}])
handmades_interiors.children.create([{name:"文房具"}])
handmades_interiors.children.create([{name:"アート/写真"}])
handmades_interiors.children.create([{name:"アロマ/キャンドル"}])
handmades_interiors.children.create([{name:"フラワー/ガーデン"}])
handmades_interiors.children.create([{name:"その他"}])

handmades_hobbies = handmades.children.create(name: "趣味/おもちゃ")
handmades_hobbies.children.create([{name:"クラフト/布製品"}])
handmades_hobbies.children.create([{name:"おもちゃ/人形"}])
handmades_hobbies.children.create([{name:"その他"}])

handmades_kids = handmades.children.create(name: "キッズ/ベビー")
handmades_kids.children.create([{name:"ファッション雑貨"}])
handmades_kids.children.create([{name:"スタイ/よだれかけ"}])
handmades_kids.children.create([{name:"外出用品"}])
handmades_kids.children.create([{name:"ネームタグ"}])
handmades_kids.children.create([{name:"その他"}])

handmades_materials = handmades.children.create(name: "素材/材料")
handmades_materials.children.create([{name:"各種パーツ"}])
handmades_materials.children.create([{name:"生地/糸"}])
handmades_materials.children.create([{name:"型紙/パターン"}])
handmades_materials.children.create([{name:"その他"}])

handmades_secondmades = handmades.children.create(name: "二次創作物")
handmades_secondmades.children.create([{name:"Ingress"}])
handmades_secondmades.children.create([{name:"クリエイターズ宇宙兄弟"}])
handmades_secondmades.children.create([{name:"その他"}])


tickets = Category.create(name: "チケット")

tickets_musics = tickets.children.create(name: "音楽  ")
tickets_musics.children.create([{name:"男性アイドル"}])
tickets_musics.children.create([{name:"女性アイドル"}])
tickets_musics.children.create([{name:"韓流"}])
tickets_musics.children.create([{name:"国内アーティスト"}])
tickets_musics.children.create([{name:"海外アーティスト"}])
tickets_musics.children.create([{name:"音楽フェス"}])
tickets_musics.children.create([{name:"声優/アニメ"}])
tickets_musics.children.create([{name:"その他"}])

tickets_sports = tickets.children.create(name: "スポーツ")
tickets_sports.children.create([{name:"サッカー"}])
tickets_sports.children.create([{name:"野球"}])
tickets_sports.children.create([{name:"テニス"}])
tickets_sports.children.create([{name:"格闘技/プロレス"}])
tickets_sports.children.create([{name:"相撲/武道"}])
tickets_sports.children.create([{name:"ゴルフ"}])
tickets_sports.children.create([{name:"バレーボール"}])
tickets_sports.children.create([{name:"バスケットボール"}])
tickets_sports.children.create([{name:"モータースポーツ"}])
tickets_sports.children.create([{name:"ウィンタースポーツ"}])
tickets_sports.children.create([{name:"その他"}])

tickets_shows = tickets.children.create(name: "演劇/芸能")
tickets_shows.children.create([{name:"ミュージカル"}])
tickets_shows.children.create([{name:"演劇"}])
tickets_shows.children.create([{name:"伝統芸能"}])
tickets_shows.children.create([{name:"落語"}])
tickets_shows.children.create([{name:"お笑い"}])
tickets_shows.children.create([{name:"オペラ"}])
tickets_shows.children.create([{name:"サーカス"}])
tickets_shows.children.create([{name:"バレエ"}])
tickets_shows.children.create([{name:"その他"}])

tickets_events = tickets.children.create(name: "イベント")
tickets_events.children.create([{name:"声優/アニメ"}])
tickets_events.children.create([{name:"キッズ/ファミリー"}])
tickets_events.children.create([{name:"トークショー/講演会"}])
tickets_events.children.create([{name:"その他"}])

tickets_movies = tickets.children.create(name: "映画")
tickets_movies.children.create([{name:"邦画"}])
tickets_movies.children.create([{name:"洋画"}])
tickets_movies.children.create([{name:"その他"}])

tickets_facilities = tickets.children.create(name: "施設利用券")
tickets_facilities.children.create([{name:"遊園地/テーマパーク"}])
tickets_facilities.children.create([{name:"美術館/博物館"}])
tickets_facilities.children.create([{name:"スキー場"}])
tickets_facilities.children.create([{name:"ゴルフ場"}])
tickets_facilities.children.create([{name:"フィットネスクラブ"}])
tickets_facilities.children.create([{name:"プール"}])
tickets_facilities.children.create([{name:"ボウリング場"}])
tickets_facilities.children.create([{name:"水族館"}])
tickets_facilities.children.create([{name:"動物園"}])
tickets_facilities.children.create([{name:"その他"}])

tickets_coupons = tickets.children.create(name: "優待券/割引券")
tickets_coupons.children.create([{name:"ショッピング"}])
tickets_coupons.children.create([{name:"レストラン/食事券"}])
tickets_coupons.children.create([{name:"フード/ドリンク券"}])
tickets_coupons.children.create([{name:"宿泊券"}])
tickets_coupons.children.create([{name:"その他"}])

tickets_others = tickets.children.create(name: "その他")


cars = Category.create(name: "自動車・オートバイ")

cars_cars = cars.children.create(name: "自動車本体")
cars_cars.children.create([{name:"国内自動車本体"}])
cars_cars.children.create([{name:"外国自動車本体"}])
cars_cars.children.create([{name:"自動車タイヤ/ホイール"}])
cars_cars.children.create([{name:"タイヤ/ホイールセット"}])
cars_cars.children.create([{name:"タイヤ"}])
cars_cars.children.create([{name:"ホイール"}])
cars_cars.children.create([{name:"その他"}])

cars_carparts = cars.children.create(name: "自動車パーツ")
cars_carparts.children.create([{name:"サスペンション"}])
cars_carparts.children.create([{name:"ブレーキ"}])
cars_carparts.children.create([{name:"外装、エアロパーツ"}])
cars_carparts.children.create([{name:"ライト"}])
cars_carparts.children.create([{name:"内装品、シート"}])
cars_carparts.children.create([{name:"ステアリング"}])
cars_carparts.children.create([{name:"マフラー・排気系"}])
cars_carparts.children.create([{name:"エンジン、過給器、冷却装置"}])
cars_carparts.children.create([{name:"クラッチ、ミッション、駆動系"}])
cars_carparts.children.create([{name:"電装品"}])
cars_carparts.children.create([{name:"補強パーツ"}])
cars_carparts.children.create([{name:"汎用パーツ"}])
cars_carparts.children.create([{name:"外国自動車用パーツ"}])
cars_carparts.children.create([{name:"その他"}])

cars_caraccesories = cars.children.create(name: "自動車アクセサリー")
cars_caraccesories.children.create([{name:"車内アクセサリー"}])
cars_caraccesories.children.create([{name:"カーナビ"}])
cars_caraccesories.children.create([{name:"カーオーディオ"}])
cars_caraccesories.children.create([{name:"車外アクセサリー"}])
cars_caraccesories.children.create([{name:"メンテナンス用品"}])
cars_caraccesories.children.create([{name:"チャイルドシート"}])
cars_caraccesories.children.create([{name:"ドライブレコーダー"}])
cars_caraccesories.children.create([{name:"レーダー探知機"}])
cars_caraccesories.children.create([{name:"カタログ/マニュアル"}])
cars_caraccesories.children.create([{name:"セキュリティ"}])
cars_caraccesories.children.create([{name:"ETC"}])
cars_caraccesories.children.create([{name:"その他"}])

cars_autobikes = cars.children.create(name: "オートバイ車体")
cars_autobikes.children.create([{name:"オートバイパーツ"}])
cars_autobikes.children.create([{name:"タイヤ"}])
cars_autobikes.children.create([{name:"マフラー"}])
cars_autobikes.children.create([{name:"エンジン、冷却装置"}])
cars_autobikes.children.create([{name:"カウル、フェンダー、外装"}])
cars_autobikes.children.create([{name:"サスペンション"}])
cars_autobikes.children.create([{name:"ホイール"}])
cars_autobikes.children.create([{name:"シート"}])
cars_autobikes.children.create([{name:"ブレーキ"}])
cars_autobikes.children.create([{name:"タンク"}])
cars_autobikes.children.create([{name:"ライト、ウィンカー"}])
cars_autobikes.children.create([{name:"チェーン、スプロケット、駆動系"}])
cars_autobikes.children.create([{name:"メーター"}])
cars_autobikes.children.create([{name:"電装系"}])
cars_autobikes.children.create([{name:"ミラー"}])
cars_autobikes.children.create([{name:"外国オートバイ用パーツ"}])
cars_autobikes.children.create([{name:"その他"}])

cars_autobikeaccesories = cars.children.create(name: "オートバイアクセサリー")
cars_autobikeaccesories.children.create([{name:"ヘルメット/シールド"}])
cars_autobikeaccesories.children.create([{name:"バイクウエア/装備"}])
cars_autobikeaccesories.children.create([{name:"アクセサリー"}])
cars_autobikeaccesories.children.create([{name:"メンテナンス"}])
cars_autobikeaccesories.children.create([{name:"カタログ/マニュアル"}])
cars_autobikeaccesories.children.create([{name:"その他"}])

others = Category.create(name: "その他")

others_matomes = others.children.create(name: "まとめ売り")
others_matomes.children.create([{name:"ペット用品"}])
others_matomes.children.create([{name:"ペットフード"}])
others_matomes.children.create([{name:"犬用品"}])
others_matomes.children.create([{name:"猫用品"}])
others_matomes.children.create([{name:"魚用品/水草"}])
others_matomes.children.create([{name:"小動物用品"}])
others_matomes.children.create([{name:"爬虫類/両生類用品"}])
others_matomes.children.create([{name:"かご/おり"}])
others_matomes.children.create([{name:"鳥用品"}])
others_matomes.children.create([{name:"虫類用品"}])
others_matomes.children.create([{name:"その他"}])

others_foods = others.children.create(name: "食品")
others_foods.children.create([{name:"菓子"}])
others_foods.children.create([{name:"米"}])
others_foods.children.create([{name:"野菜"}])
others_foods.children.create([{name:"果物"}])
others_foods.children.create([{name:"調味料"}])
others_foods.children.create([{name:"魚介類(加工食品)"}])
others_foods.children.create([{name:"肉類(加工食品)"}])
others_foods.children.create([{name:"その他 加工食品"}])
others_foods.children.create([{name:"その他"}])

others_alcholes = others.children.create(name: "飲料/酒")
others_alcholes.children.create([{name:"コーヒー"}])
others_alcholes.children.create([{name:"ソフトドリンク"}])
others_alcholes.children.create([{name:"ミネラルウォーター"}])
others_alcholes.children.create([{name:"茶"}])
others_alcholes.children.create([{name:"ウイスキー"}])
others_alcholes.children.create([{name:"ワイン"}])
others_alcholes.children.create([{name:"ブランデー"}])
others_alcholes.children.create([{name:"焼酎"}])
others_alcholes.children.create([{name:"日本酒"}])
others_alcholes.children.create([{name:"ビール、発泡酒"}])
others_alcholes.children.create([{name:"その他"}])

others_zakkas = others.children.create(name: "日用品/生活雑貨/旅行")
others_zakkas.children.create([{name:"タオル/バス用品"}])
others_zakkas.children.create([{name:"日用品/生活雑貨"}])
others_zakkas.children.create([{name:"洗剤/柔軟剤"}])
others_zakkas.children.create([{name:"旅行用品"}])
others_zakkas.children.create([{name:"防災関連グッズ"}])
others_zakkas.children.create([{name:"その他"}])

others_antiques = others.children.create(name: "アンティーク/コレクション")
others_antiques.children.create([{name:"雑貨"}])
others_antiques.children.create([{name:"工芸品"}])
others_antiques.children.create([{name:"家具"}])
others_antiques.children.create([{name:"印刷物"}])
others_antiques.children.create([{name:"その他"}])

others_stationaries = others.children.create(name: "文房具/事務用品")
others_stationaries.children.create([{name:"筆記具"}])
others_stationaries.children.create([{name:"ノート/メモ帳"}])
others_stationaries.children.create([{name:"テープ/マスキングテープ"}])
others_stationaries.children.create([{name:"カレンダー/スケジュール"}])
others_stationaries.children.create([{name:"アルバム/スクラップ"}])
others_stationaries.children.create([{name:"ファイル/バインダー"}])
others_stationaries.children.create([{name:"はさみ/カッター"}])
others_stationaries.children.create([{name:"カードホルダー/名刺管理"}])
others_stationaries.children.create([{name:"のり/ホッチキス"}])
others_stationaries.children.create([{name:"その他"}])

others_jimus = others.children.create(name: "事務/店舗用品")
others_jimus.children.create([{name:"オフィス用品一般"}])
others_jimus.children.create([{name:"オフィス家具"}])
others_jimus.children.create([{name:"店舗用品"}])
others_jimus.children.create([{name:"OA機器"}])
others_jimus.children.create([{name:"ラッピング/包装"}])
others_jimus.children.create([{name:"その他"}])

others_others = others.children.create(name: "その他")
